---
# file: tasks/main.yml

- name: Install apache2 & mod-wsgi
  apt: name={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - libapache2-mod-rpaf

- name: Configure apache2 ports
  template: src="ports.conf.j2" dest="/etc/apache2/ports.conf" owner=root group=root mode=0644
  register: reload_apache

- name: Restart apache2 service
  when: reload_apache is defined and reload_apache|changed
  service: name=apache2 state=restarted

- name: Enable mod-wsgi & mod-rpaf apache2 modules
  command: /usr/sbin/a2enmod {{ item.mod }} creates={{ item.link }}
  with_items:
    - { mod: "wsgi", link: "/etc/apache2/mods-enabled/wsgi.load" }
    - { mod: "rpaf", link: "/etc/apache2/mods-enabled/rpaf.load" }
  notify: reload apache2

- name: Start & enable apache2 service
  service: name=apache2 state=started enabled=yes

# vim: set sw=2 ts=2:
